#ifndef _GLOBAL_ENUM_H__
#define _GLOBAL_ENUM_H__

enum _PANEL_TYPE {
	PANEL_SPECTRUM = 0,
	PANEL_SPECTRUM_CPU,
	PANEL_SPECTRUM_MEMORY,
	PANEL_SPECTRUM_PAGEFILE,
//	PANEL_TOTALINFO_CPU,
//	PANEL_TOTALINFO_MEMORY,
//	PANEL_TOTALINFO_PAGE_FILE,
	PANEL_CPU_GRAPH,
	PANEL_CPU_GRAPH_TOTAL,
	PANEL_CPU_CORE_GRAPH,
	PANEL_PROCESS_TOTAL,
	PANEL_PROCESS_CPU,
	PANEL_PROCESS_MEMORY
};

#endif
