#ifndef _GLOBAL_ENUM_H__
#define _GLOBAL_ENUM_H__
/*
enum _PANEL_TYPE {
	PANEL_SPECTRUM = 0,
	PANEL_SPECTRUM_CPU,
	PANEL_SPECTRUM_MEMORY,
	PANEL_SPECTRUM_PAGEFILE,
//	PANEL_TOTALINFO_CPU,
//	PANEL_TOTALINFO_MEMORY,
//	PANEL_TOTALINFO_PAGE_FILE,
	PANEL_CPU_GRAPH,
	PANEL_CPU_GRAPH_TOTAL,
	PANEL_CPU_CORE_GRAPH,
	PANEL_PROCESS_TOTAL,
	PANEL_PROCESS_CPU,
	PANEL_PROCESS_MEMORY
};
*/
enum USAGE_TYPE {
	USAGE_NONE = 0,
	USAGE_CPU,
	USAGE_MEMORY_PHYSIC,
	USAGE_MEMORY_VIRTUAL,
	USAGE_MEMORY_PAGEFILE,
	USAGE_MAX
};

enum PROCESSLIST_PRIORITY_TYPE {
	PROCESSLIST_PRIORITY_ALL = 0,
	PROCESSLIST_PRIORITY_CPU,
	PROCESSLIST_PRIORITY_MEM,
	PROCESSLIST_PRIORITY_MAX
};

enum PROCESS_POSITION {
	POS_NONE = 0,
	POS_LEFT,
	POS_RIGHT,
	POS_TOP,
	POS_BOTTOM
};

enum _MENU_EVENT_TYPE {
	_MENU_EVENT_NONE = -1,
	_MENU_FILE_NEW_JOB_EXEC,
	_MENU_FILE_PROGRAM_TERMINATE,
	_MENU_TOOL_SETENV,
	_MENU_TOOL_SAVE
};

#endif
